name: deploy
on:
 push:
  branches:
   - master

env:
  AWS_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ROLE_ARN: arn:aws:iam::726059925999:role/github-role

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build UI
        run: yarn run build

      - name: Deploy backend
        run: yarn run deploy:backend

      - name: Deploy UI
        run: yarn run deploy:ui
      